"""broadcast buttons+gif, menu images, miniapp ui overrides

Revision ID: a68a369a14c4
Revises: 3c3a765fca32
Create Date: 2026-07-07 02:22:32.008893
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import src.infrastructure.database.base  # noqa: F401  (custom column types in autogen)
from sqlalchemy.dialects import postgresql

revision: str = "a68a369a14c4"
down_revision: str | None = "3c3a765fca32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("broadcasts", sa.Column("button_action", sa.String(length=64), nullable=True))
    op.add_column("broadcasts", sa.Column("button_color", sa.String(length=9), nullable=True))
    op.add_column("broadcasts", sa.Column("emoji_id", sa.String(length=32), nullable=True))
    op.add_column("menu_nodes", sa.Column("image_path", sa.String(length=512), nullable=True))
    op.add_column(
        "miniapp_config",
        sa.Column(
            "ui",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("miniapp_config", "ui")
    op.drop_column("menu_nodes", "image_path")
    op.drop_column("broadcasts", "emoji_id")
    op.drop_column("broadcasts", "button_color")
    op.drop_column("broadcasts", "button_action")
    # ### end Alembic commands ###
