"""Deploy/update integrity — guards the whole update mechanism against the failure classes
that actually bricked real updates, so it can never regress silently.

Covered here (all runnable without Docker):
* every Compose ``${VAR:?}`` REQUIRED interpolation var is generated by install.sh —
  a fresh install can never boot with a missing required var (e.g. DATABASE__PASSWORD);
* no shell script or doc invokes ``docker compose -f docker/compose.prod.yml`` WITHOUT
  ``--env-file`` (the exact «required variable DATABASE__PASSWORD is missing a value»
  footgun) — they must go through ``scripts/dc.sh`` or pass the env file explicitly;
* every shell script parses (``bash -n``);
* the running version is consistent across pyproject / constants;
* the dc.sh convenience wrapper exists, is executable, and passes ``--env-file``.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
COMPOSE = REPO / "docker" / "compose.prod.yml"
INSTALL = REPO / "scripts" / "install.sh"
DC = REPO / "scripts" / "dc.sh"


def _required_compose_vars() -> set[str]:
    """Vars written as ``${NAME:?...}`` in the prod compose — Compose aborts if any is unset."""
    text = COMPOSE.read_text()
    return set(re.findall(r"\$\{([A-Z_]+):\?", text))


def test_required_compose_vars_are_generated_by_installer() -> None:
    required = _required_compose_vars()
    assert "DATABASE__PASSWORD" in required, "sanity: the DB password must be a required var"
    install = INSTALL.read_text()
    for var in required:
        # install.sh must write a NON-EMPTY value for each required var (``VAR=$SOMETHING``),
        # or a fresh install boots straight into the interpolation error the client hit.
        assert re.search(rf"^{re.escape(var)}=\S", install, re.MULTILINE), (
            f"install.sh must generate a non-empty {var} "
            f"(compose marks it required with ${{{var}:?}})"
        )


def _shell_scripts() -> list[Path]:
    return sorted(REPO.glob("scripts/*.sh"))


def _doc_files() -> list[Path]:
    docs: list[Path] = []
    for base in ("docs", "docs-site"):
        root = REPO / base
        if root.is_dir():
            # only human-authored markdown — skip the generated VitePress build output
            docs += [p for p in root.rglob("*.md") if ".vitepress/dist" not in str(p)]
    for name in ("README.md",):
        if (REPO / name).is_file():
            docs.append(REPO / name)
    return docs


def test_no_bare_compose_command_in_scripts_or_docs() -> None:
    """A ``docker compose -f docker/compose.prod.yml`` without ``--env-file`` resolves ${VAR}
    against the compose file's dir (docker/), not the repo root, and dies with «required
    variable DATABASE__PASSWORD is missing a value». Every such command must pass --env-file
    (scripts do) or go through scripts/dc.sh (docs do)."""
    offenders: list[str] = []
    for path in _shell_scripts() + _doc_files():
        for i, line in enumerate(path.read_text().splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("#"):
                continue  # a shell/markdown comment explaining the footgun isn't a command
            if "docker compose -f docker/compose.prod.yml" in line and "--env-file" not in line:
                offenders.append(f"{path.relative_to(REPO)}:{i}: {stripped}")
    assert not offenders, (
        "Use scripts/dc.sh (or add --env-file .env) — a bare compose command against the "
        "prod file fails interpolation:\n" + "\n".join(offenders)
    )


def test_env_grep_substitutions_are_failure_tolerant() -> None:
    """A ``VAR=$(grep '^KEY=' .env …)`` under ``set -o pipefail`` aborts the whole script when the
    key is absent (grep returns 1) — this silently killed a real update right after a successful
    rebuild. Every such command substitution must end with ``|| true`` / ``|| :``. Regression."""
    pat = re.compile(r"^\s*[A-Za-z_][A-Za-z0-9_]*=\$\(grep\b[^)]*\.env\b[^)]*\)")
    offenders: list[str] = []
    for script in _shell_scripts():
        if "set -o pipefail" not in script.read_text() and "set -euo" not in script.read_text():
            continue
        for i, line in enumerate(script.read_text().splitlines(), 1):
            if line.strip().startswith("#"):
                continue
            if pat.search(line) and not re.search(r"\|\|\s*(true|:)\s*\)", line):
                offenders.append(f"{script.relative_to(REPO)}:{i}: {line.strip()}")
    assert not offenders, (
        "A grep-miss on an optional .env key returns 1 and aborts the script under pipefail — "
        "guard each with `|| true`:\n" + "\n".join(offenders)
    )


@pytest.mark.parametrize("script", _shell_scripts(), ids=lambda p: p.name)
def test_shell_scripts_are_syntactically_valid(script: Path) -> None:
    bash = shutil.which("bash")
    if bash is None:
        pytest.skip("bash not available")
    result = subprocess.run([bash, "-n", str(script)], capture_output=True, text=True)
    assert result.returncode == 0, f"{script.name} has a syntax error:\n{result.stderr}"


def test_dc_wrapper_exists_and_passes_env_file() -> None:
    assert DC.is_file(), "scripts/dc.sh convenience wrapper must exist"
    text = DC.read_text()
    assert "--env-file .env" in text and "docker/compose.prod.yml" in text
    # executable bit so operators can run ./scripts/dc.sh directly
    import os

    assert os.access(DC, os.X_OK), "scripts/dc.sh must be executable (chmod +x)"


def test_version_is_consistent_across_manifests() -> None:
    """pyproject version and the runtime APP_VERSION must match — the update checker and the
    cabinet both surface APP_VERSION, and a drift makes «current version» lie."""
    pyproject = (REPO / "pyproject.toml").read_text()
    m = re.search(r'^version\s*=\s*"([^"]+)"', pyproject, re.MULTILINE)
    assert m, "pyproject.toml must declare a version"
    pyproject_version = m.group(1)

    constants = (REPO / "src" / "core" / "constants.py").read_text()
    m2 = re.search(r'APP_VERSION[^=]*=\s*"([^"]+)"', constants)
    assert m2, "constants.py must declare APP_VERSION"
    assert pyproject_version == m2.group(1), (
        f"version drift: pyproject={pyproject_version} APP_VERSION={m2.group(1)} — bump both"
    )
